# 使用 PyTorch aarch64镜像作为基础
FROM kumatea/pytorch

# 其他 Docker 指令，例如设置工作目录、复制文件等。

# 设置工作目录
WORKDIR /app

# 将 torch 文件夹的内容复制到容器的 /app 目录中
COPY ./torch /app

# 安装项目所需的依赖
RUN pip install --no-cache-dir -r requirements.txt

# 设置 Flask 环境变量
ENV FLASK_APP=/app/torch-backend-api.py
ENV FLASK_RUN_HOST=0.0.0.0

# 暴露端口 999
EXPOSE 999

# 运行 Flask 应用
CMD ["python", "/app/torch-backend-api.py"]

